<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\SicossConceptosArca;

class SicossConceptosArcaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $conceptos = [
            ['codigo' => '110000', 'descripcion' => 'Sueldo'],
            ['codigo' => '110001', 'descripcion' => 'Preaviso'],
            ['codigo' => '110002', 'descripcion' => 'Remuneracion en especies'],
            ['codigo' => '110003', 'descripcion' => 'Comida'],
            ['codigo' => '110004', 'descripcion' => 'Habitación'],
            ['codigo' => '110005', 'descripcion' => 'Licencias por estudio'],
            ['codigo' => '110006', 'descripcion' => 'Donación de sangre'],
            ['codigo' => '110007', 'descripcion' => 'Feriado'],
            ['codigo' => '110008', 'descripcion' => 'Prest. Dineraria Ley 24577 (primeros 10d)'],
            ['codigo' => '110009', 'descripcion' => 'Prest. Dineraria Ley 24577 (a cargo de ART)'],
            ['codigo' => '110010', 'descripcion' => 'Sueldo - Uso para aplicación RG 2252 - Actividades simultáneas'],
            ['codigo' => '110011', 'descripcion' => 'Incremento solidario - Dec. 14/2020'],
            ['codigo' => '111000 al 119999', 'descripcion' => 'Sueldo - De uso libre'],
            ['codigo' => '120000', 'descripcion' => 'Sueldo anual complementario'],
            ['codigo' => '120001', 'descripcion' => 'SAC 1er semestre'],
            ['codigo' => '120002', 'descripcion' => 'SAC 2do semestre'],
            ['codigo' => '120003', 'descripcion' => 'SAC proporcional'],
            ['codigo' => '120004', 'descripcion' => 'SAC - Uso para aplicación RG 2252 - Actividades simultáneas'],
            ['codigo' => '121000 al 129999', 'descripcion' => 'SAC - De uso libre'],
            ['codigo' => '130000', 'descripcion' => 'Horas extras'],
            ['codigo' => '130001', 'descripcion' => 'Horas extras al 50 %'],
            ['codigo' => '130002', 'descripcion' => 'Horas extras al 100 %'],
            ['codigo' => '130003', 'descripcion' => 'Horas extras al 200 %'],
            ['codigo' => '130004', 'descripcion' => 'Horas extras - Uso para aplicación RG 2252 - Actividades simultáneas'],
            ['codigo' => '131000 al 139999', 'descripcion' => 'Horas extras - De uso libre'],
            ['codigo' => '140000', 'descripcion' => 'Zona desfavorable'],
            ['codigo' => '140001', 'descripcion' => 'Zona desfavorable - Uso para aplicación RG 2252 - Actividades simultáneas'],
            ['codigo' => '141000 al 149999', 'descripcion' => 'Zona desfavorable - De uso libre'],
            ['codigo' => '150000', 'descripcion' => 'Adelanto vacacional'],
            ['codigo' => '150001', 'descripcion' => 'Adelanto vacacional - Uso para aplicación RG 2252 - Actividades simultáneas'],
            ['codigo' => '151000 al 159999', 'descripcion' => 'Adelanto vacacional - De uso libre'],
            ['codigo' => '160000', 'descripcion' => 'Adicionales'],
            ['codigo' => '160001', 'descripcion' => 'Adicional por antiguedad'],
            ['codigo' => '160002', 'descripcion' => 'Adicional por título'],
            ['codigo' => '160003', 'descripcion' => 'Adicional por tarea'],
            ['codigo' => '160004', 'descripcion' => 'Adicional por desarraigo'],
            ['codigo' => '160005', 'descripcion' => 'Adicionales - Uso para aplicación RG 2252 - Actividades simultáneas'],
            ['codigo' => '161000 al 169999', 'descripcion' => 'Adicionales - De uso libre'],
            ['codigo' => '170000', 'descripcion' => 'Gratificaciones y/o Premios'],
            ['codigo' => '170001', 'descripcion' => 'Premio por presentismo'],
            ['codigo' => '170002', 'descripcion' => 'Premio por producción'],
            ['codigo' => '170003', 'descripcion' => 'Comisiones'],
            ['codigo' => '170004', 'descripcion' => 'Accesorios'],
            ['codigo' => '170005', 'descripcion' => 'Viáticos sin comprobante'],
            ['codigo' => '170006', 'descripcion' => 'Propinas habituales no prohibidas'],
            ['codigo' => '170007', 'descripcion' => 'Gratificaciones y/o Premios - Uso para aplicación RG 2252 - Actividades simultáneas'],
            ['codigo' => '171000 al 179999', 'descripcion' => 'Gratificaciones y/o Premios - De uso libre'],
            ['codigo' => '180000', 'descripcion' => 'Rectificativa por remuneración Ley 27.742'],
            ['codigo' => '510000', 'descripcion' => 'Asignaciones Familiares'],
            ['codigo' => '510001', 'descripcion' => 'Ayuda escolar'],
            ['codigo' => '510002', 'descripcion' => 'Asignación por hijo/hijo con discapacidad'],
            ['codigo' => '510003', 'descripcion' => 'Asignación por maternidad'],
            ['codigo' => '510004', 'descripcion' => 'Asignación por maternidad down'],
            ['codigo' => '510005', 'descripcion' => 'Asignación por matrimonio'],
            ['codigo' => '510006', 'descripcion' => 'Asignación por nacimiento / adopción'],
            ['codigo' => '510007', 'descripcion' => 'Asignación por prenatal'],
            ['codigo' => '511000 al 519999', 'descripcion' => 'Asignaciones Familiares - De uso libre'],
            ['codigo' => '520000', 'descripcion' => 'Beneficios sociales'],
            ['codigo' => '520001', 'descripcion' => 'Servicio de comedor'],
            ['codigo' => '520002', 'descripcion' => 'Gastos médicos'],
            ['codigo' => '520003', 'descripcion' => 'Provisión de ropa de trabajo'],
            ['codigo' => '520004', 'descripcion' => 'Guardería'],
            ['codigo' => '520005', 'descripcion' => 'Provisión de útiles escolares'],
            ['codigo' => '520006', 'descripcion' => 'Gastos de sepelio'],
            ['codigo' => '520007', 'descripcion' => 'Cursos de capacitación'],
            ['codigo' => '520008', 'descripcion' => 'Becas'],
            ['codigo' => '520009', 'descripcion' => 'Desempleo'],
            ['codigo' => '520010', 'descripcion' => 'Gratificación por cese laboral'],
            ['codigo' => '520011', 'descripcion' => 'Indemnización por extinción del contrato de trabajo'],
            ['codigo' => '520012', 'descripcion' => 'Vacaciones no gozadas'],
            ['codigo' => '520013', 'descripcion' => 'Incapacidad permanente'],
            ['codigo' => '520014', 'descripcion' => 'Indemización por despido'],
            ['codigo' => '520015', 'descripcion' => 'Indemización sustitutiva del preaviso'],
            ['codigo' => '520016', 'descripcion' => 'Integración mes de despido'],
            ['codigo' => '520017', 'descripcion' => 'SAC sobre integración o preaviso'],
            ['codigo' => '520018', 'descripcion' => 'SAC sobre vacaciones no gozadas'],
            ['codigo' => '521000 al 529999', 'descripcion' => 'Beneficios sociales - De uso libre'],
            ['codigo' => '530000', 'descripcion' => 'Incrementos no remunerativos (con aportes OS)'],
            ['codigo' => '531000 al 539999', 'descripcion' => 'Incrementos no remunerativos (con aportes OS) - De uso libre'],
            ['codigo' => '540000', 'descripcion' => 'Incrementos no remunerativos (con aportes y contribuciones OS)'],
            ['codigo' => '541000 al 549999', 'descripcion' => 'Incrementos no remunerativos (con aportes y contribuciones OS) - De uso libre'],
            ['codigo' => '550000', 'descripcion' => 'Importes no remunerativos especiales'],
            ['codigo' => '551000 al 559999', 'descripcion' => 'Importes no remunerativos especiales - De uso libre'],
            ['codigo' => '560000', 'descripcion' => 'Mensual - PPC y CCT Especiales'],
            ['codigo' => '560001', 'descripcion' => 'SAC - PPC y CCT Especiales'],
            ['codigo' => '560002', 'descripcion' => 'SAC  Proporcional- PPC y CCT Especiales'],
            ['codigo' => '560003', 'descripcion' => 'Vacaciones - PPC y CCT Especiales'],
            ['codigo' => '560004', 'descripcion' => 'Asign. dineraria progr. sociales, educativos o empleo - Dec. 551/2022'],
            ['codigo' => '560005', 'descripcion' => 'Asign. No remunerativa Dec 841/2022'],
            ['codigo' => '560006', 'descripcion' => 'Asignación No Remunerativa Dec. 438/2023'],
            ['codigo' => '570000', 'descripcion' => 'Mensual - Remuneracion No Contributiva al Régimen Nacional de Seguridad Social'],
            ['codigo' => '570001', 'descripcion' => 'SAC - Remuneracion No Contributiva al Régimen Nacional de Seguridad Social'],
            ['codigo' => '570002', 'descripcion' => 'SAC Proporcional - Remuneración No Contributiva al Régimen Nacional de Seguridad Social'],
            ['codigo' => '570003', 'descripcion' => 'Vacaciones - Remuneracion No Contributiva al Régimen Nacional de Seguridad Social'],
            ['codigo' => '799999', 'descripcion' => 'Redondeo (No Remunerativo)'],
            ['codigo' => '810000', 'descripcion' => 'Sistema previsional'],
            ['codigo' => '810001', 'descripcion' => 'INSSJyP'],
            ['codigo' => '810002', 'descripcion' => 'Obra Social'],
            ['codigo' => '810003', 'descripcion' => 'Fondo Solidario de Redistribución (ex ANSSAL)'],
            ['codigo' => '810004', 'descripcion' => 'Cuota Sindical'],
            ['codigo' => '810005', 'descripcion' => 'Seguro de Vida'],
            ['codigo' => '810006', 'descripcion' => 'RENATEA (ex RENATRE)'],
            ['codigo' => '810007', 'descripcion' => 'Préstamos'],
            ['codigo' => '810008', 'descripcion' => 'Impuesto a las Ganancias'],
            ['codigo' => '810009', 'descripcion' => 'Obra Social - Adherentes'],
            ['codigo' => '810010', 'descripcion' => 'Fondo Solidario de Redistribución (ex ANSSAL) - Adherentes'],
            ['codigo' => '810011', 'descripcion' => 'Ajuste Aporte Dec. 561/2019'],
            ['codigo' => '810012', 'descripcion' => 'Salario complementario. Dec 332/2020'],
            ['codigo' => '810013', 'descripcion' => 'SAC ajuste base imponible'],
            ['codigo' => '810014', 'descripcion' => 'Pago a cuenta Asign. dineraria progr. sociales, educativos o empleo - Dec. 551/2022'],
            ['codigo' => '810015', 'descripcion' => 'Sistema previsional no nacional'],
            ['codigo' => '810016', 'descripcion' => 'Obra Social provincial'],
            ['codigo' => '820000', 'descripcion' => 'Otros descuentos'],
            ['codigo' => 'del 821000 al 829999', 'descripcion' => 'Otros descuentos - De uso libre'],
        ];

        foreach ($conceptos as $concepto) {
            SicossConceptosArca::updateOrCreate(
                ['codigo' => $concepto['codigo']],
                ['descripcion' => $concepto['descripcion']]
            );
        }
    }
}

