<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SicossObrasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = now();

        $rows = [
            ['codigo' => 3009,   'detalle' => 'O.S.PERSONAL ASOCIADO A ASOC.MUTUAL SANCOR (O.S.PERS.A.A.M.S)'],
            ['codigo' => 905008, 'detalle' => 'ADMINISTRACIÓN RECURSOS PARA SALUD S.A.'],
            ['codigo' => 905503, 'detalle' => 'AGRUPACION SANATORIAL SUR S.A.'],
            ['codigo' => 905107, 'detalle' => 'AMSTERDAM SALUD S.A.'],
            ['codigo' => 905800, 'detalle' => 'ANDESALUD SOCIEDAD ANÓNIMA'],
            ['codigo' => 902801, 'detalle' => 'APRES SOCIEDAD ANONIMA'],
            ['codigo' => 901600, 'detalle' => 'ASISTENCIA SANITARIA INTEGRAL S.A.'],
            ['codigo' => 903002, 'detalle' => 'ASOCIACION CIVIL DE ESTUDIOS SUPERIORES ACES (HOSPITAL AUSTRAL)'],
            ['codigo' => 600408, 'detalle' => 'ASOCIACION DE OBRAS SOCIALES DE COMODORO RIVADAVIA'],
            ['codigo' => 602305, 'detalle' => 'ASOCIACION DE OBRAS SOCIALES DE ROSARIO'],
            ['codigo' => 603100, 'detalle' => 'ASOCIACION DE OBRAS SOCIALES DE TRELEW'],
            ['codigo' => 905404, 'detalle' => 'ASOCIACION MUTUAL DE FARMACEUTICOS FLORENTINO AMEGHINO'],
            ['codigo' => 901808, 'detalle' => 'ASOCIACION MUTUAL DE PARTICIPANTES DE ECONOMIA SOLIDARIAS'],
            ['codigo' => 902306, 'detalle' => 'ASOCIACION MUTUAL DEL PERSONAL, ASESORES Y DIRECTIVOS DE GRUPO SAN NICOLAS S.R.L'],
            ['codigo' => 900300, 'detalle' => 'ASOCIACION MUTUAL RURALISTA'],
            ['codigo' => 902108, 'detalle' => 'ASOCIACION MUTUAL SANCOR SALUD'],
            ['codigo' => 900904, 'detalle' => 'ASOCIACIÓN MUTUAL DE SALUD DE CIUDADELA'],
            ['codigo' => 904708, 'detalle' => 'ASOCIACIÓN MUTUAL DEL CONTROL INTEGRAL'],
            ['codigo' => 904609, 'detalle' => 'ASOCIACIÓN MUTUAL FRANCO ANDINA REGIONAL MENDOZA'],
            ['codigo' => 904401, 'detalle' => 'ASOCIACIÓN MUTUAL MÉDICA DE VILLA MARÍA'],
            ['codigo' => 903101, 'detalle' => 'AVALIAN SALUD Y BIENESTAR COOPERATIVA LIMITADA'],
            ['codigo' => 905909, 'detalle' => 'BONMED SOCIEDAD ANÓNIMA'],
            ['codigo' => 902603, 'detalle' => 'CENTRO DE EDUCACION MEDICA E INVESTIGACIONES CLINICAS NORBERTO QUIRNO - CEMIC'],
            ['codigo' => 905206, 'detalle' => 'CIRCULO MEDICO DE LOMAS DE ZAMORA'],
            ['codigo' => 904302, 'detalle' => 'COBERTURA DE SALUD S.A.'],
            ['codigo' => 900508, 'detalle' => 'CYNTHIOS SALUD S.A.'],
            ['codigo' => 903606, 'detalle' => 'ENSALUD SA'],
            ['codigo' => 901105, 'detalle' => 'GALENO ARGENTINA SOCIEDAD ANONIMA'],
            ['codigo' => 904005, 'detalle' => 'GEA S.A.'],
            ['codigo' => 903804, 'detalle' => 'GERMED S A'],
            ['codigo' => 905305, 'detalle' => 'GILSA S.R.L.'],
            ['codigo' => 903309, 'detalle' => 'GRUPO DDM SA'],
            ['codigo' => 905701, 'detalle' => 'GRUPO MEDICO INCAS S.A.'],
            ['codigo' => 901204, 'detalle' => 'HOSPITAL ALEMAN ASOCIACION CIVIL'],
            ['codigo' => 902504, 'detalle' => 'HOSPITAL BRITANICO DE BUENOS AIRES ASOCIACION CIVIL'],
            ['codigo' => 500807, 'detalle' => 'INSTITUTO NACIONAL DE SERVICIOS SOCIALES PARA JUBILADOS Y PENSIONADOS'],
            ['codigo' => 900409, 'detalle' => 'LA CASA DEL MEDICO MUTUAL'],
            ['codigo' => 901501, 'detalle' => 'MEDICINA PREPAGA HOMINIS S.A.'],
            ['codigo' => 901006, 'detalle' => 'MEDICUS SOCIEDAD ANONIMA DE ASISTENCIA MEDICA Y CIENTIFICA'],
            ['codigo' => 901402, 'detalle' => 'MEDIFE ASOCIACION CIVIL'],
            ['codigo' => 904500, 'detalle' => 'MEDYCIN ARGENTINO S.A.'],
            ['codigo' => 903903, 'detalle' => 'MET CORDOBA SA'],
            ['codigo' => 703,    'detalle' => 'MUTUAL DEL PERSONAL DE AGUA Y ENERGIA DE MENDOZA'],
            ['codigo' => 905602, 'detalle' => 'MUTUAL DEL PERSONAL DEL CENTRO INDUSTRIAL ACINDAR'],
            ['codigo' => 903200, 'detalle' => 'MUTUAL FEDERADA 25 DE JUNIO SOCIEDAD DE PROTECCION RECIPROCA'],
            ['codigo' => 901709, 'detalle' => 'MUTUAL MEDICA CONCORDIA'],
            ['codigo' => 902207, 'detalle' => 'NATIVUS SOCIEDAD DE RESPONSABILIDAD LIMITADA'],
            ['codigo' => 904906, 'detalle' => 'NOBIS S.A.'],
            ['codigo' => 2907,   'detalle' => 'O. S. ASOCIACION MUTUAL METALURGICA VILLA CONSTITUCION (O.S.A.M.M.V.C)'],
            ['codigo' => 402707, 'detalle' => 'O.S. DE DIRECCION OSDO'],
            ['codigo' => 2600,   'detalle' => 'O.S. DE LA TRABAJADORES DE LA CARNE Y AFINES DE LA R.A.'],
            ['codigo' => 112103, 'detalle' => 'O.S. DE LA UNION OBRERA METALURGICO DE LA REPUBLICA ARGENTINA'],
            ['codigo' => 120702, 'detalle' => 'O.S. DEL PERSONAL DE LAS TELECOMUNICACIONES DE LA REPUBLICA ARGENTINA'],
            ['codigo' => 2402,   'detalle' => 'O.S. DEL PERSONAL JERARQUICO DEL TRANSPORTE AUTOMOTOR DE PASAJEROS DE CORDOBA Y AFINES'],
            ['codigo' => 128409, 'detalle' => 'O.S. DEL SINDICATO OBREROS Y EMPLEADOS DE EMPRESAS DE LIMPIEZA, SERVICIOS Y AFINES DE CORDOBA'],
            ['codigo' => 2303,   'detalle' => 'O.S. PARA EL PERSONAL DE EMPRESAS DE LIMPIEZA, SERVICIOS Y MAESTRANZA DE MENDOZA'],
            ['codigo' => 127604, 'detalle' => 'O.S. PARA EL PERSONAL DE OBRAS Y SERVICIOS SANITARIOS'],
            ['codigo' => 2105,   'detalle' => 'O.S. PROFESIONALES DEL TURF DE LA REPUBLICA ARGENTINA'],
            ['codigo' => 400909, 'detalle' => 'O.S.ACCION SOCIAL DE EMPRESARIOS'],
            ['codigo' => 800501, 'detalle' => 'O.S.ACEROS PARANA'],
            ['codigo' => 125905, 'detalle' => 'O.S.ARBITROS DEPORTIVOS DE LA REPUBLICA ARGENTINA'],
            ['codigo' => 402103, 'detalle' => 'O.S.ASOCIACION DEL PERSONAL DE DIRECCION DE LA INDUSTRIA SIDERURGICA'],
            ['codigo' => 402301, 'detalle' => 'O.S.ASOCIACION DEL PERSONAL SUPERIOR DE LA ORGANIZACIÓN TECHINT'],
            ['codigo' => 401803, 'detalle' => 'O.S.ASOCIACION MUTUAL DEL PERSONAL DE PHILIPS ARGENTINA (AMPAR)'],
            ['codigo' => 126304, 'detalle' => 'O.S.BANCARIA ARGENTINA'],
            ['codigo' => 303307, 'detalle' => 'O.S.CABOT ARGENTINA'],
            ['codigo' => 400701, 'detalle' => 'O.S.CAMARA DE LA INDUSTRIA CURTIDORA ARGENTINA'],
            ['codigo' => 300704, 'detalle' => 'O.S.CERAS JOHNSON'],
            ['codigo' => 121804, 'detalle' => 'O.S.CONDUCTORES DE TAXIS DE CORDOBA'],
            ['codigo' => 400305, 'detalle' => 'O.S.COOPERATIVA LIMITADA DE ASISTENCIA MEDICA, FARMACEUTICA, CREDITO Y CONSUMO DEL PERSONAL SUPERIOR DE LA INDUSTRIA DEL CAUCHO Y OTRAS ACTIVIDADES INDUSTRIALES'],
            ['codigo' => 100205, 'detalle' => 'O.S.DE ACTORES'],
            ['codigo' => 100809, 'detalle' => 'O.S.DE AERONAVEGANTES'],
            ['codigo' => 604,    'detalle' => 'O.S.DE AGENTES DE LOTERIAS Y AFINES DE LA REPUBLICA ARGENTINA'],
            ['codigo' => 118309, 'detalle' => 'O.S.DE AGENTES DE PROPAGANDA MEDICA DE CORDOBA'],
            ['codigo' => 118408, 'detalle' => 'O.S.DE AGENTES DE PROPAGANDA MEDICA DE ENTRE RIOS'],
            ['codigo' => 118200, 'detalle' => 'O.S.DE AGENTES DE PROPAGANDA MEDICA DE LA REPUBLICA ARGENTINA'],
            ['codigo' => 124001, 'detalle' => 'O.S.DE BOXEADORES AGREMIADOS DE LA REPUBLICA ARGENTINA'],
            ['codigo' => 116105, 'detalle' => 'O.S.DE CAPATACES Y ESTIBADORES PORTUARIOS'],
            ['codigo' => 111506, 'detalle' => 'O.S.DE CAPITANES BAQUEANOS FLUVIALES DE LA MARINA MERCANTE'],
            ['codigo' => 111407, 'detalle' => 'O.S.DE CAPITANES DE ULTRAMAR Y OFICIALES DE LA MARINA MERCANTE'],
            ['codigo' => 505,    'detalle' => 'O.S.DE CAPITANES, PILOTOS Y PATRONES DE PESCA'],
            ['codigo' => 104108, 'detalle' => 'O.S.DE CERAMISTAS'],
            ['codigo' => 105804, 'detalle' => 'O.S.DE CHOFERES DE CAMIONES'],
            ['codigo' => 104801, 'detalle' => 'O.S.DE COLOCADORES DE AZULEJOS, MOSAICOS, GRANITEROS, LUSTRADORES Y PORCELANEROS'],
            ['codigo' => 113809, 'detalle' => 'O.S.DE COMISARIOS NAVALES'],
            ['codigo' => 103204, 'detalle' => 'O.S.DE CONDUCTORES CAMIONEROS Y PERSONAL DEL TRANSPORTE AUTOMOTOR DE CARGAS'],
            ['codigo' => 121606, 'detalle' => 'O.S.DE CONDUCTORES DE TRANSPORTE COLECTIVO DE PASAJEROS'],
            ['codigo' => 105002, 'detalle' => 'O.S.DE CONDUCTORES NAVALES (CONDUCTORES FUSIONADOS)'],
            ['codigo' => 106302, 'detalle' => 'O.S.DE DOCENTES PARTICULARES'],
            ['codigo' => 100908, 'detalle' => 'O.S.DE EMPLEADOS DE AGENCIAS DE INFORMES'],
            ['codigo' => 122401, 'detalle' => 'O.S.DE EMPLEADOS DE LA INDUSTRIA DEL VIDRIO'],
            ['codigo' => 111605, 'detalle' => 'O.S.DE EMPLEADOS DE LA MARINA MERCANTE'],
            ['codigo' => 118002, 'detalle' => 'O.S.DE EMPLEADOS DE PRENSA DE CORDOBA'],
            ['codigo' => 120603, 'detalle' => 'O.S.DE EMPLEADOS DEL TABACO'],
            ['codigo' => 121101, 'detalle' => 'O.S.DE EMPLEADOS TEXTILES Y AFINES'],
            ['codigo' => 111704, 'detalle' => 'O.S.DE ENCARGADOS APUNTADORES MARITIMOS'],
            ['codigo' => 108209, 'detalle' => 'O.S.DE FOTOGRAFOS'],
            ['codigo' => 108605, 'detalle' => 'O.S.DE FUTBOLISTAS'],
            ['codigo' => 109202, 'detalle' => 'O.S.DE GUINCHEROS Y MAQUINISTAS DE GRUAS MOVILES'],
            ['codigo' => 110107, 'detalle' => 'O.S.DE JARDINEROS, PARQUISTAS, VIVERISTAS Y FLORICULTORES'],
            ['codigo' => 113304, 'detalle' => 'O.S.DE JEFES Y OFICIALES MAQUINISTAS NAVALES'],
            ['codigo' => 113205, 'detalle' => 'O.S.DE JEFES Y OFICIALES NAVALES DE RADIOCOMUNICACIONES'],
            ['codigo' => 901,    'detalle' => 'O.S.DE LA ACTIVIDAD DE SEGUROS, REASEGUROS, CAPITALIZACION Y AHORRO Y PRESTAMO PARA LA VIVIENDA'],
            ['codigo' => 112400, 'detalle' => 'O.S.DE LA ACTIVIDAD MINERA'],
            ['codigo' => 200400, 'detalle' => 'O.S.DE LA EMPRESA NACIONAL DE CORREOS Y TELEGRAFOS S.A. Y DE LAS COMUNICACIONES DE LA REPUBLICA ARGENTINA'],
            ['codigo' => 110701, 'detalle' => 'O.S.DE LA FEDERACION ARGENTINA DE TRABAJADORES DE LUZ Y FUERZA'],
            ['codigo' => 125509, 'detalle' => 'O.S.DE LA FEDERACION ARGENTINA DEL TRABAJADOR DE LAS UNIVERSIDADES NACIONALES'],
            ['codigo' => 1904,   'detalle' => 'O.S.DE LA FEDERACION DE CAMARAS Y CENTROS COMERCIALES ZONALES DE LA REPUBLICA ARGENTINA'],
            ['codigo' => 114208, 'detalle' => 'O.S.DE LA INDUSTRIA DE PASTAS ALIMENTICIAS'],
            ['codigo' => 121507, 'detalle' => 'O.S.DE LA INDUSTRIA DEL TRANSPORTE AUTOMOTOR DE CORDOBA'],
            ['codigo' => 110602, 'detalle' => 'O.S.DE LOCUTORES'],
            ['codigo' => 105507, 'detalle' => 'O.S.DE LOS CORTADORES DE LA INDUMENTARIA'],
            ['codigo' => 126205, 'detalle' => 'O.S.DE LOS EMPLEADOS DE COMERCIO Y ACTIVIDADES CIVILES'],
            ['codigo' => 125103, 'detalle' => 'O.S.DE LOS PROFESIONALES UNIVERSITARIOS DEL AGUA Y ENERGIA ELECTRICA'],
            ['codigo' => 112202, 'detalle' => 'O.S.DE LOS SUPERVISORES DE LA INDUSTRIA METALMECANICA DE LA REPUBLICA ARGENTINA'],
            ['codigo' => 126106, 'detalle' => 'O.S.DE LOS TRABAJADORES DE LA EDUCACION PRIVADA'],
            ['codigo' => 124506, 'detalle' => 'O.S.DE LOS TRABAJADORES DE LA INDUSTRIA DEL GAS'],
            ['codigo' => 110800, 'detalle' => 'O.S.DE LOS TRABAJADORES DE LAS EMPRESAS DE ELECTRICIDAD'],
            ['codigo' => 111308, 'detalle' => 'O.S.DE MAQUINISTAS DE TEATRO Y TELEVISION'],
            ['codigo' => 2501,   'detalle' => 'O.S.DE MINISTROS, SECRETARIOS Y SUBSECRETARIOS'],
            ['codigo' => 112806, 'detalle' => 'O.S.DE MUSICOS'],
            ['codigo' => 106708, 'detalle' => 'O.S.DE OBREROS EMPACADORES DE FRUTA DE RIO NEGRO Y NEUQUEN'],
            ['codigo' => 114901, 'detalle' => 'O.S.DE OFICIALES PELUQUEROS Y PEINADORES DE ROSARIO'],
            ['codigo' => 104603, 'detalle' => 'O.S.DE OPERADORES CINEMATOGRAFICOS'],
            ['codigo' => 114000, 'detalle' => 'O.S.DE PANADEROS, PASTELEROS Y FACTUREROS DE ENTRE RIOS'],
            ['codigo' => 114307, 'detalle' => 'O.S.DE PASTELEROS, CONFITEROS, PIZZEROS Y ALFAJOREROS DE LA REPUBLICA ARGENTINA'],
            ['codigo' => 114505, 'detalle' => 'O.S.DE PATRONES DE CABOTAJE DE RIOS Y PUERTOS'],
            ['codigo' => 123701, 'detalle' => 'O.S.DE PEONES DE TAXIS DE LA CAPITAL FEDERAL'],
            ['codigo' => 115508, 'detalle' => 'O.S.DE PETROLEROS DE CORDOBA'],
            ['codigo' => 115706, 'detalle' => 'O.S.DE PILOTOS DE LINEAS AEREAS COMERCIALES Y REGULARES'],
            ['codigo' => 116204, 'detalle' => 'O.S.DE PORTUARIOS ARGENTINOS'],
            ['codigo' => 118804, 'detalle' => 'O.S.DE RECIBIDORES DE GRANOS Y ANEXOS'],
            ['codigo' => 119203, 'detalle' => 'O.S.DE RELOJEROS Y JOYEROS'],
            ['codigo' => 119906, 'detalle' => 'O.S.DE SERENOS DE BUQUES'],
            ['codigo' => 123107, 'detalle' => 'O.S.DE TALLERISTAS A DOMICILIO'],
            ['codigo' => 108704, 'detalle' => 'O.S.DE TECNICOS DE FUTBOL'],
            ['codigo' => 115102, 'detalle' => 'O.S.DE TRABADORES DE PRENSA DE BUENOS AIRES'],
            ['codigo' => 127000, 'detalle' => 'O.S.DE TRABAJADORES DE ESTACIONES DE SERVICIO (OSTES)'],
            ['codigo' => 120801, 'detalle' => 'O.S.DE TRABAJADORES DE LAS COMUNICACIONES (OSTRAC)'],
            ['codigo' => 123602, 'detalle' => 'O.S.DE TRABAJADORES DE PERKINS ARGENTINA S.A.I.C.'],
            ['codigo' => 121903, 'detalle' => 'O.S.DE VAREADORES'],
            ['codigo' => 123909, 'detalle' => 'O.S.DE VENDEDORES AMBULANTES DE LA REPUBLICA ARGENTINA'],
            ['codigo' => 122104, 'detalle' => 'O.S.DE VIAJANTES VENDEDORES DE LA REPUBLICA ARGENTINA'],
            ['codigo' => 105309, 'detalle' => 'O.S.DEL PERSONAL ADMINISTRATIVO Y TECNICO DE LA CONSTRUCCION Y AFINES'],
            ['codigo' => 100502, 'detalle' => 'O.S.DEL PERSONAL AERONAUTICO'],
            ['codigo' => 100601, 'detalle' => 'O.S.DEL PERSONAL AERONAVEGACION DE ENTES PRIVADOS'],
            ['codigo' => 103600, 'detalle' => 'O.S.DEL PERSONAL AUXILIAR DE CASAS PARTICULARES'],
            ['codigo' => 125707, 'detalle' => 'O.S.DEL PERSONAL CIVIL DE LA NACION'],
            ['codigo' => 106005, 'detalle' => 'O.S.DEL PERSONAL DE ENTIDADES DEPORTIVAS Y CIVILES'],
            ['codigo' => 101000, 'detalle' => 'O.S.DEL PERSONAL DE AGUAS GASEOSAS Y AFINES'],
            ['codigo' => 101802, 'detalle' => 'O.S.DEL PERSONAL DE AZUCAR DEL INGENIO LA ESPERANZA'],
            ['codigo' => 101901, 'detalle' => 'O.S.DEL PERSONAL DE AZUCAR DEL INGENIO LEDESMA'],
            ['codigo' => 102300, 'detalle' => 'O.S.DEL PERSONAL DE AZUCAR DEL INGENIO SAN MARTIN'],
            ['codigo' => 102904, 'detalle' => 'O.S.DEL PERSONAL DE BARRACAS DE LANAS,CUEROS Y ANEXOS'],
            ['codigo' => 103402, 'detalle' => 'O.S.DEL PERSONAL DE CARGA Y DESCARGA'],
            ['codigo' => 104009, 'detalle' => 'O.S.DEL PERSONAL DE CEMENTERIOS DE LA REPUBLICA ARGENTINA'],
            ['codigo' => 109301, 'detalle' => 'O.S.DEL PERSONAL DE CONSIGNATARIOS DEL MERCADO NACIONAL DE HACIENDA DE LINIERS'],
            ['codigo' => 401100, 'detalle' => 'O.S.DEL PERSONAL DE DIRECCION ALFREDO FORTABAT'],
            ['codigo' => 120405, 'detalle' => 'O.S.DEL PERSONAL DE DIRECCION DE LA EMPRESA SUBTERRANEOS BUENOS AIRES'],
            ['codigo' => 400206, 'detalle' => 'O.S.DEL PERSONAL DE DIRECCION DE LA INDUSTRIA AUTOMOTRIZ ARGENTINA'],
            ['codigo' => 400404, 'detalle' => 'O.S.DEL PERSONAL DE DIRECCION DE LA INDUSTRIA CERVECERA Y MALTERA'],
            ['codigo' => 401209, 'detalle' => 'O.S.DEL PERSONAL DE DIRECCION DE LA INDUSTRIA METALURGICA Y DEMAS ACT. EMPRESARIAS'],
            ['codigo' => 401605, 'detalle' => 'O.S.DEL PERSONAL DE DIRECCION DE LA INDUSTRIA PRIVADA DEL PETROLEO'],
            ['codigo' => 402400, 'detalle' => 'O.S.DEL PERSONAL DE DIRECCION DE LA INDUSTRIA VITIVINICOLA Y AFINES'],
            ['codigo' => 402004, 'detalle' => 'O.S.DEL PERSONAL DE DIRECCION DE LA SANIDAD LUIS PASTEUR'],
            ['codigo' => 400107, 'detalle' => 'O.S.DEL PERSONAL DE DIRECCION DE LAS EMPRESAS DE LA ALIMENTACION Y DEMAS ACTIVIDADES EMPRESARIAS'],
            ['codigo' => 401001, 'detalle' => 'O.S.DEL PERSONAL DE DIRECCION DE LAS EMPRESAS QUE ACTUAN EN FRUTOS DEL PAIS'],
            ['codigo' => 401902, 'detalle' => 'O.S.DEL PERSONAL DE DIRECCION DE PERFUMERIAS E.W.HOPE'],
            ['codigo' => 400503, 'detalle' => 'O.S.DEL PERSONAL DE DIRECCION Y JERARQUICO DE LA INDUSTRIA DEL CIGARRILLO'],
            ['codigo' => 106203, 'detalle' => 'O.S.DEL PERSONAL DE DISTRIBUIDORAS CINEMATOGRAFICAS'],
            ['codigo' => 106401, 'detalle' => 'O.S.DEL PERSONAL DE EDIFCIOS DE RENTA Y HORIZONTAL DE LA REPUBLICA ARGENTINA'],
            ['codigo' => 106500, 'detalle' => 'O.S.DEL PERSONAL DE EDIFICIOS DE RENTAS Y HORIZONTAL DE CAPITAL FEDERAL Y GRAN BUENOS ARIES'],
            ['codigo' => 900102, 'detalle' => 'O.S.DEL PERSONAL DE EMPRESAS FIAT Y EMPRESAS PEUGEOT CITROEN ARG.'],
            ['codigo' => 106906, 'detalle' => 'O.S.DEL PERSONAL DE ESCRIBANIAS DE LA PROVINCIA DE BUENOS AIRES'],
            ['codigo' => 107008, 'detalle' => 'O.S.DEL PERSONAL DE ESCRIBANOS'],
            ['codigo' => 107206, 'detalle' => 'O.S.DEL PERSONAL DE ESTACIONES DE SERVICIO Y GNC,GARAGES,PLAYAS DE ESTACIONAMIENTO Y LAVADEROS AUTOMATICOS'],
            ['codigo' => 122906, 'detalle' => 'O.S.DEL PERSONAL DE ESTACIONES DE SERVICIO,GARAGES,PLAYAS DE ESTACIONAMIENTO Y LAVADEROS AUTOMATICOS DE SANTA FE'],
            ['codigo' => 115805, 'detalle' => 'O.S.DEL PERSONAL DE FABRICAS DE PINTURA'],
            ['codigo' => 107404, 'detalle' => 'O.S.DEL PERSONAL DE FARMACIA'],
            ['codigo' => 109707, 'detalle' => 'O.S.DEL PERSONAL DE IMPRENTA, DIARIOS Y AFINES'],
            ['codigo' => 118705, 'detalle' => 'O.S.DEL PERSONAL DE INDUSTRIAS QUIMICAS Y PETROQUIMICAS'],
            ['codigo' => 119609, 'detalle' => 'O.S.DEL PERSONAL DE INSTALACIONES SANITARIAS'],
            ['codigo' => 110008, 'detalle' => 'O.S.DEL PERSONAL DE JABONEROS'],
            ['codigo' => 108407, 'detalle' => 'O.S.DEL PERSONAL DE LA ACTIVIDAD FRUCTICOLA'],
            ['codigo' => 104306, 'detalle' => 'O.S.DEL PERSONAL DE LA ACTIVIDAD CERVECERA Y AFINES'],
            ['codigo' => 121705, 'detalle' => 'O.S.DEL PERSONAL DE LA ACTIVIDAD DEL TURF'],
            ['codigo' => 115003, 'detalle' => 'O.S.DEL PERSONAL DE LA ACTIVIDAD PERFUMISTA'],
            ['codigo' => 122302, 'detalle' => 'O.S.DEL PERSONAL DE LA ACTIVIDAD VIAL'],
            ['codigo' => 122609, 'detalle' => 'O.S.DEL PERSONAL DE LA ACTIVIDAD VITIVINICOLA'],
            ['codigo' => 104207, 'detalle' => 'O.S.DEL PERSONAL DE LA CERAMICA,SANITARIOS,PORCELANAS DE MESA Y AFINES'],
            ['codigo' => 105408, 'detalle' => 'O.S.DEL PERSONAL DE LA CONSTRUCCION'],
            ['codigo' => 106807, 'detalle' => 'O.S.DEL PERSONAL DE LA ENSEÑANZA PRIVADA'],
            ['codigo' => 102706, 'detalle' => 'O.S.DEL PERSONAL DE LA INDUSTRIA AZUCARERA'],
            ['codigo' => 103006, 'detalle' => 'O.S.DEL PERSONAL DE LA INDUSTRIA BOTONERA'],
            ['codigo' => 104504, 'detalle' => 'O.S.DEL PERSONAL DE LA INDUSTRIA CINEMATOGRAFICA'],
            ['codigo' => 101208, 'detalle' => 'O.S.DEL PERSONAL DE LA INDUSTRIA DE LA ALIMENTACION'],
            ['codigo' => 103105, 'detalle' => 'O.S.DEL PERSONAL DE LA INDUSTRIA DEL CALZADO'],
            ['codigo' => 103709, 'detalle' => 'O.S.DEL PERSONAL DE LA INDUSTRIA DEL CAUCHO'],
            ['codigo' => 103907, 'detalle' => 'O.S.DEL PERSONAL DE LA INDUSTRIA DEL CAUCHO DE SANTA FE'],
            ['codigo' => 105705, 'detalle' => 'O.S.DEL PERSONAL DE LA INDUSTRIA DEL CHACINADO Y AFINES'],
            ['codigo' => 105606, 'detalle' => 'O.S.DEL PERSONAL DE LA INDUSTRIA DEL CUERO Y AFINES'],
            ['codigo' => 107800, 'detalle' => 'O.S.DEL PERSONAL DE LA INDUSTRIA DEL FIBROCEMENTO'],
            ['codigo' => 108100, 'detalle' => 'O.S.DEL PERSONAL DE LA INDUSTRIA DEL FOSFORO'],
            ['codigo' => 109400, 'detalle' => 'O.S.DEL PERSONAL DE LA INDUSTRIA DEL HIELO Y MERCADOS PARTICULARES'],
            ['codigo' => 113601, 'detalle' => 'O.S.DEL PERSONAL DE LA INDUSTRIA DEL NEUMATICO'],
            ['codigo' => 115201, 'detalle' => 'O.S.DEL PERSONAL DE LA INDUSTRIA DEL PESCADO DE MAR DEL PLATA'],
            ['codigo' => 116006, 'detalle' => 'O.S.DEL PERSONAL DE LA INDUSTRIA DEL PLASTICO'],
            ['codigo' => 120504, 'detalle' => 'O.S.DEL PERSONAL DE LA INDUSTRIA DEL TABACO'],
            ['codigo' => 121309, 'detalle' => 'O.S.DEL PERSONAL DE LA INDUSTRIA DEL TRACTOR'],
            ['codigo' => 122500, 'detalle' => 'O.S.DEL PERSONAL DE LA INDUSTRIA DEL VIDRIO'],
            ['codigo' => 107909, 'detalle' => 'O.S.DEL PERSONAL DE LA INDUSTRIA FIDEERA'],
            ['codigo' => 108001, 'detalle' => 'O.S.DEL PERSONAL DE LA INDUSTRIA FORESTAL DE SANTIAGO DEL ESTERO'],
            ['codigo' => 208,    'detalle' => 'O.S.DEL PERSONAL DE LA INDUSTRIA GRAFICA DE LA PROVINCIA DE CORDOBA'],
            ['codigo' => 110404, 'detalle' => 'O.S.DEL PERSONAL DE LA INDUSTRIA LADRILLERA A MAQUINA'],
            ['codigo' => 110503, 'detalle' => 'O.S.DEL PERSONAL DE LA INDUSTRIA LECHERA'],
            ['codigo' => 111001, 'detalle' => 'O.S.DEL PERSONAL DE LA INDUSTRIA MADERERA'],
            ['codigo' => 112608, 'detalle' => 'O.S.DEL PERSONAL DE LA INDUSTRIA MOLINERA'],
            ['codigo' => 113700, 'detalle' => 'O.S.DEL PERSONAL DE LA INDUSTRIA NAVAL'],
            ['codigo' => 115607, 'detalle' => 'O.S.DEL PERSONAL DE LA INDUSTRIA PETROQUIMICA'],
            ['codigo' => 121002, 'detalle' => 'O.S.DEL PERSONAL DE LA INDUSTRIA TEXTIL'],
            ['codigo' => 118606, 'detalle' => 'O.S.DEL PERSONAL DE LA PUBLICIDAD'],
            ['codigo' => 119500, 'detalle' => 'O.S.DEL PERSONAL DE LA SANIDAD ARGENTINA'],
            ['codigo' => 109509, 'detalle' => 'O.S.DEL PERSONAL DE LOS HIPODROMOS DE BUENOS AIRES Y SAN ISIDRO'],
            ['codigo' => 110909, 'detalle' => 'O.S.DEL PERSONAL DE LUZ Y FUERZA DE CORDOBA'],
            ['codigo' => 111209, 'detalle' => 'O.S.DEL PERSONAL DE MAESTRANZA'],
            ['codigo' => 108506, 'detalle' => 'O.S.DEL PERSONAL DE MANIPULEO,EMPAQUE Y EXPEDICION DE FRUTA FRESCA Y HORTALIZAS DE CUYO'],
            ['codigo' => 112301, 'detalle' => 'O.S.DEL PERSONAL DE MICROS Y OMNIBUS DE MENDOZA'],
            ['codigo' => 406,    'detalle' => 'O.S.DEL PERSONAL DE ORGANISMOS DE CONTROL EXTERNO'],
            ['codigo' => 113908, 'detalle' => 'O.S.DEL PERSONAL DE PANADERIAS'],
            ['codigo' => 303703, 'detalle' => 'O.S.DEL PERSONAL DE PBBPOLISUR DE BAHIA BLANCA'],
            ['codigo' => 114703, 'detalle' => 'O.S.DEL PERSONAL DE PELUQUERIAS,ESTETICA Y AFINES'],
            ['codigo' => 117405, 'detalle' => 'O.S.DEL PERSONAL DE PRENSA DE BAHIA BLANCA'],
            ['codigo' => 117207, 'detalle' => 'O.S.DEL PERSONAL DE PRENSA DE LA REPUBLICA ARGENTINA'],
            ['codigo' => 117702, 'detalle' => 'O.S.DEL PERSONAL DE PRENSA DE MAR DEL PLATA'],
            ['codigo' => 117801, 'detalle' => 'O.S.DEL PERSONAL DE PRENSA DE MENDOZA'],
            ['codigo' => 123404, 'detalle' => 'O.S.DEL PERSONAL DE PRENSA DE ROSARIO'],
            ['codigo' => 123503, 'detalle' => 'O.S.DEL PERSONAL DE PRENSA DE TUCUMAN'],
            ['codigo' => 118903, 'detalle' => 'O.S.DEL PERSONAL DE RECOLECCION Y BARRIDO DE ROSARIO'],
            ['codigo' => 119005, 'detalle' => 'O.S.DEL PERSONAL DE REFINERIAS DE MAIZ'],
            ['codigo' => 119708, 'detalle' => 'O.S.DEL PERSONAL DE SEGURIDAD COMERCIAL,INDUSTRIAL E INVESTIGACIONES PRIVADAS'],
            ['codigo' => 303406, 'detalle' => 'O.S.DEL PERSONAL DE SHELL-CAPSA'],
            ['codigo' => 123305, 'detalle' => 'O.S.DEL PERSONAL DE SOCIEDADES DE AUTORES Y AFINES'],
            ['codigo' => 120306, 'detalle' => 'O.S.DEL PERSONAL DE SUPERVISION DE LA EMPRESA SUBTERRANEOS DE BUENOS AIRES'],
            ['codigo' => 120900, 'detalle' => 'O.S.DEL PERSONAL DE TELEVISION'],
            ['codigo' => 122807, 'detalle' => 'O.S.DEL PERSONAL DE VIGILANCIA Y SEGURIDAD COMERCIAL,INDUSTRIAL E INVESTIGACIONES PRIVADAS DE CORDOBA'],
            ['codigo' => 101604, 'detalle' => 'O.S.DEL PERSONAL DEL AUTOMOVIL CLUB ARGENTINO'],
            ['codigo' => 103808, 'detalle' => 'O.S.DEL PERSONAL DEL CAUCHO'],
            ['codigo' => 107107, 'detalle' => 'O.S.DEL PERSONAL DEL ESPECTACULO PUBLICO'],
            ['codigo' => 110206, 'detalle' => 'O.S.DEL PERSONAL DEL JOCKEY CLUB DE ROSARIO'],
            ['codigo' => 114109, 'detalle' => 'O.S.DEL PERSONAL DEL PAPEL,CARTON Y QUIMICOS'],
            ['codigo' => 400602, 'detalle' => 'O.S.DEL PERSONAL DIRECTIVO DE LA INDUSTRIA DE LA CONSTRUCCION'],
            ['codigo' => 109004, 'detalle' => 'O.S.DEL PERSONAL GRAFICO'],
            ['codigo' => 1706,   'detalle' => 'O.S.DEL PERSONAL JERARQUICO DE LA REPUBLICA ARGENTINA PARA EL PERSONAL JERARQUICO DE LA INDUSTRIA GRAFICA Y EL PERSONAL JERARQUICO DE AGUA Y ENERGIA'],
            ['codigo' => 110305, 'detalle' => 'O.S.DEL PERSONAL LADRILLERO'],
            ['codigo' => 111803, 'detalle' => 'O.S.DEL PERSONAL MARITIMO'],
            ['codigo' => 112707, 'detalle' => 'O.S.DEL PERSONAL MOSAISTA'],
            ['codigo' => 700108, 'detalle' => 'O.S.DEL PERSONAL MUNICIPAL DE AVELLANEDA'],
            ['codigo' => 700801, 'detalle' => 'O.S.DEL PERSONAL MUNICIPAL DE LA MATANZA'],
            ['codigo' => 701002, 'detalle' => 'O.S.DEL PERSONAL MUNICIPAL DE TRES DE FEBRERO'],
            ['codigo' => 113403, 'detalle' => 'O.S.DEL PERSONAL NAVAL'],
            ['codigo' => 119302, 'detalle' => 'O.S.DEL PERSONAL RURAL Y ESTIBADORES DE LA REPUBLICA ARGENTINA'],
            ['codigo' => 112004, 'detalle' => 'O.S.DEL PERSONAL SUPERIOR DE MERCEDES BENZ ARGENTINA'],
            ['codigo' => 100403, 'detalle' => 'O.S.DEL PERSONAL SUPERIOR Y PROFESIONAL DE EMPRESAS AEROCOMERCIALES'],
            ['codigo' => 100700, 'detalle' => 'O.S.DEL PERSONAL TECNICO AERONAUTICO'],
            ['codigo' => 115409, 'detalle' => 'O.S.DEL PETROLEO Y GAS PRIVADO'],
            ['codigo' => 111902, 'detalle' => 'O.S.DEL SINDICATO DE MECANICOS Y AFINES DEL TRANSPORTE AUTOMOTOR'],
            ['codigo' => 1607,   'detalle' => 'O.S.DEL SINDICATO UNIDO DE TRABAJADORES DE LA INDUSTRIA DE AGUAS GASEOSAS DE LA PROVINCIA DE SANTA FE'],
            ['codigo' => 106609, 'detalle' => 'O.S.ELECTRICISTAS NAVALES'],
            ['codigo' => 106104, 'detalle' => 'O.S.EMPLEADOS DE DESPACHANTES DE ADUANA'],
            ['codigo' => 401704, 'detalle' => 'O.S.EMPRESARIOS,PROFESIONALES Y MONOTRIBUTISTAS'],
            ['codigo' => 126007, 'detalle' => 'O.S.FEDERACION GREMIAL INDUSTRIA DE LA CARNE Y SUS DERIVADOS'],
            ['codigo' => 125301, 'detalle' => 'O.S.FEDERAL NACIONAL DE OBRAS SANITARIAS'],
            ['codigo' => 1300,   'detalle' => 'O.S.FERROVIARIA'],
            ['codigo' => 303901, 'detalle' => 'O.S.FORD ARGENTINA S.A.'],
            ['codigo' => 112509, 'detalle' => 'O.S.MODELOS ARGENTINOS'],
            ['codigo' => 402202, 'detalle' => 'O.S.MUTUALIDAD INDUSTRIAL TEXTIL ARGENTINA'],
            ['codigo' => 302106, 'detalle' => 'O.S.PARA DIRECTIVOS,TECNICOS Y EMPLEADOS DE JOHN DEERE ARGENTINA'],
            ['codigo' => 401308, 'detalle' => 'O.S.PARA EL PERSONAL DE DIRECCION DE LA INDUSTRIA MADERERA'],
            ['codigo' => 123008, 'detalle' => 'O.S.PARA EL PERSONAL DE ESTACIONES DE SERVICIO,GARAGES,PLAYAS DE ESTACIONAMIENTO,LAVADEROS AUTOMATICOS Y GOMERIAS DE LA REPUBLICA ARGENTINA'],
            ['codigo' => 100106, 'detalle' => 'O.S.PARA EL PERSONAL DE LA INDUSTRIA ACEITERA Y AFINES'],
            ['codigo' => 122005, 'detalle' => 'O.S.PARA EL PERSONAL DE LA INDUSTRIA DEL VESTIDO Y AFINES'],
            ['codigo' => 1201,   'detalle' => 'O.S.PARA EL PERSONAL DEL MINISTERIO DE ECONOMIA Y OBRAS PUBLICAS'],
            ['codigo' => 1102,   'detalle' => 'O.S.PARA LA ACTIVIDAD DOCENTE'],
            ['codigo' => 126601, 'detalle' => 'O.S.PERSONAL DE INDUSTRIAS QUIMICAS Y PETROQUIMICAS ZARATE CAMPANA'],
            ['codigo' => 115300, 'detalle' => 'O.S.PETROLEROS'],
            ['codigo' => 307,    'detalle' => 'O.S.PORTUARIOS ARGENTINOS DE MAR DEL PLATA'],
            ['codigo' => 116709, 'detalle' => 'O.S.PORTUARIOS DE PUERTO SAN MARTIN Y BELLA VISTA'],
            ['codigo' => 302809, 'detalle' => 'O.S.REFINERIAS DE MAIZ S.A.I.C.F.'],
            ['codigo' => 303109, 'detalle' => 'O.S.SUPERCO'],
            ['codigo' => 304003, 'detalle' => 'O.S.VOLKSWAGEN ARGENTINA S.A.'],
            ['codigo' => 109608, 'detalle' => 'O.S.Y SINDICATO DEL PERSONAL MENSUALIZADO DEL JOCKEY CLUB DE BUENOS AIRES Y LOS HIPODROMOS DE PALERMO Y SAN ISIDRO'],
            ['codigo' => 129006, 'detalle' => 'OBRA SOCIAL DE LA ASOCIACIÓN DEL PERSONAL SUPERIOR DE EPEC'],
            ['codigo' => 3801,   'detalle' => 'OBRA SOCIAL DE LA PREVENCIÓN Y LA SALUD'],
            ['codigo' => 128102, 'detalle' => 'OBRA SOCIAL DE LA UNION DE TRABAJADORES DEL INSSJyP'],
            ['codigo' => 126908, 'detalle' => 'OBRA SOCIAL DE LOS MEDICOS DE LA CIUDAD DE BUENOS AIRES'],
            ['codigo' => 128904, 'detalle' => 'OBRA SOCIAL DE LOS TRABAJADORES ARGENTINOS DE CENTROS DE CONTACTOS'],
            ['codigo' => 128300, 'detalle' => 'OBRA SOCIAL DE PEONES DE TAXI DE ROSARIO'],
            ['codigo' => 128607, 'detalle' => 'OBRA SOCIAL DE TRABAJADORES DEL PETROLEO Y GAS PRIVADO DEL CHUBUT'],
            ['codigo' => 128706, 'detalle' => 'OBRA SOCIAL DEL PERSONAL DE DRAGADO Y BALIZAMIENTO'],
            ['codigo' => 128201, 'detalle' => 'OBRA SOCIAL DEL SINDICATO UNIC DE RECOLECTORES DE RESIDUOS Y BARRIDO DE CORDOBA'],
            ['codigo' => 128508, 'detalle' => 'OBRA SOCIAL FARMACEUTICOS Y BIOQUIMICOS'],
            ['codigo' => 4002,   'detalle' => 'OBRA SOCIAL PARA EMPLEADOS Y PRODUCTORES DE ENTIDADES DE LA ACTIVIDAD AGROPECUARIA Y AGROALIMENTARIA DE LA ENCONOMIA SOCIAL'],
            ['codigo' => 3603,   'detalle' => 'OBRA SOCIAL PROGRAMAS MEDICOS SOCIEDAD ARGENTINA DE CONSULTORIA MUTUAL'],
            ['codigo' => 3900,   'detalle' => 'OBRA SOCIAL TÉCNICOS DE VUELO LINEAS AEREAS'],
            ['codigo' => 3702,   'detalle' => 'OBRA SOCIAL YACIMIENTOS CARBONIFEROS'],
            ['codigo' => 902900, 'detalle' => 'OMINT SOCIEDAD ANONlMA DE SERVICIOS'],
            ['codigo' => 400800, 'detalle' => 'ORGANIZACION DE SERVICIOS DIRECTOS EMPRESARIOS'],
            ['codigo' => 402608, 'detalle' => 'OS ASOCIACION DE SERVICIOS SOCIALES PARA EMPRESARIOS Y PERSONAL DE DIRECCION DE EMPRESAS DEL COMERCIO, SERVICIOS, PRODUCCION, INDUSTRIA Y CIVIL (ASPE)'],
            ['codigo' => 3504,   'detalle' => 'OS CONDUCTORES TITULARES DE TAXIS DE LA CDAD AUT. BS.AS.'],
            ['codigo' => 126502, 'detalle' => 'OS CONFEDERACION DE OBREROS Y EMPLEADOS MUNICIPALES ARGENTINA'],
            ['codigo' => 126809, 'detalle' => 'OS DE CONDUCTORES DE REMISES Y AUTOS AL INSTANTE Y AFINES'],
            ['codigo' => 402806, 'detalle' => 'OS DE DIRECCION DE LA ACTIVIDAD AEROCOMERCIAL PRIVADA'],
            ['codigo' => 3405,   'detalle' => 'OS DE LA ASOCIACION MUTUAL DE LOS OBREROS CATOLICOS PADRE FEDERICO GROTE'],
            ['codigo' => 2808,   'detalle' => 'OS DE LA CAMARA DE EMPRESARIOS DE AGENCIAS DE REMISES DE LA PROVINCIA DE BUENOS AIRES (O.S.C.E.A.R.B.A)'],
            ['codigo' => 127505, 'detalle' => 'OS DE LAS ASOCIACIONES DE EMPLEADOS DE FARMACIA (OSADEF)'],
            ['codigo' => 3108,   'detalle' => 'OS DE LOS INMIGRANTES ESPANOLES Y SUS DESCENDIENTES RESIDENTES DE LA RA'],
            ['codigo' => 2709,   'detalle' => 'OS DE LOS TRABAJADORES ASOCIADOS A LA ASOCIACION MUTUAL MERCANTIL ARGENTINA (OSTAMMA)'],
            ['codigo' => 127802, 'detalle' => 'OS DE LUZ Y FUERZA DE LA PATAGONIA'],
            ['codigo' => 127208, 'detalle' => 'OS DE MANDOS MEDIOS DE LAS TELECOMUNICACIONES DE LA RA Y EL MERCOSUR - OSMMEDT'],
            ['codigo' => 127406, 'detalle' => 'OS DE OBREROS Y EMPLEADOS TINTOREROS, SOMBREROS Y LAVADEROS DE LA R.A.'],
            ['codigo' => 127901, 'detalle' => 'OS DE PETROLEROS PRIVADOS'],
            ['codigo' => 3207,   'detalle' => 'OS DE TRABAJADORES SOCIOS DE LA ASOCIACION MUTUAL DEL PERSONAL JERARQUICO DE BANCOS OFICIALES - JERARQUICO SALUD'],
            ['codigo' => 127307, 'detalle' => 'OS DE TRABAJADORES VIALES Y AFINES DE LA REPUBLICA ARGENTINA'],
            ['codigo' => 126700, 'detalle' => 'OS DEL PERSONAL DE LA ACTIVIDAD AZUCARERA TUCUMANA'],
            ['codigo' => 128003, 'detalle' => 'OS DEL PERSONAL DE LA FEDERACION DE SINDICATOS DE LA INDUSTRIA QUIMICA Y PETROQUIMICA'],
            ['codigo' => 108803, 'detalle' => 'OS DEL PERSONAL DE LA UNION DE TRABAJADORES DEL TURISMO, HOTELEROS Y GASTRONOMICOS DE LA RA (OSUTHGRA)'],
            ['codigo' => 127109, 'detalle' => 'OS DEL PERSONAL DE LAS TELECOMUNICACIONES SINDICATO BS AS (OSPETELCO)'],
            ['codigo' => 127703, 'detalle' => 'OS PERSONAL ESTACIONES DE SERVICIO, GARAGES, PLAYAS Y LAVADEROS DE LA PCIA. CHACO'],
            ['codigo' => 3306,   'detalle' => 'OS TRABAJADORES VENDEDORES DE DIARIOS, REVISTAS Y AFINES (OSTVENDRA)'],
            ['codigo' => 402509, 'detalle' => 'OS YPF'],
            ['codigo' => 1508,   'detalle' => 'OS. ASOCIACION CIVIL PRO SINDICATO AMAS DE CASA DE LA REPUBLICA ARGENTINA'],
            ['codigo' => 2204,   'detalle' => 'OS. EMPLEADOS Y PERSONAL JERARQUICO DEL NEUMATICO ARGENTINO DE NEUMATICOS GOOD YEAR S.R.L.'],
            ['codigo' => 1805,   'detalle' => 'Obra Social de Legisladores de la Republica Argentina'],
            ['codigo' => 902009, 'detalle' => 'PARQUE SALUD S.A.'],
            ['codigo' => 902405, 'detalle' => 'PLENIMEDICAL S.A.'],
            ['codigo' => 904203, 'detalle' => 'PREMEDICA S.A.'],
            ['codigo' => 900706, 'detalle' => 'PRESTADORES SANATORIALES SA'],
            ['codigo' => 903507, 'detalle' => 'PREVENCIÓN SALUD S.A.'],
            ['codigo' => 904104, 'detalle' => 'PRIVAMED S.A.'],
            ['codigo' => 903408, 'detalle' => 'ROI S A'],
            ['codigo' => 900607, 'detalle' => 'SABER SOCIEDAD ANÖNIMA'],
            ['codigo' => 904807, 'detalle' => 'SCIS S.A.'],
            ['codigo' => 903705, 'detalle' => 'SISTEMA INTEGRADO DE PRESTADORES DE SALUD S A'],
            ['codigo' => 902702, 'detalle' => 'SOCIEDAD ITALIANA DE BENEFICENCIA EN BUENOS AIRES'],
            ['codigo' => 901907, 'detalle' => 'SOREMER S.A.'],
            ['codigo' => 900805, 'detalle' => 'SWISS MEDICAL SA'],
            ['codigo' => 0,      'detalle' => 'Sin Obra Social'],
        ];

        // Normalizar + timestamps
        $rows = array_map(function ($r) use ($now) {
            $r['detalle'] = mb_substr(trim($r['detalle']), 0, 255);
            $r['codigo'] = (int) $r['codigo'];
            $r['created_at'] = $now;
            $r['updated_at'] = $now;
            return $r;
        }, $rows);

        DB::table('sicoss_obras')->upsert(
            $rows,
            ['codigo'],
            ['detalle', 'updated_at']
        );
    }
}
